<a href="https://colab.research.google.com/github/Justinemmerich/VideoPose3D/blob/master/Notebook/Facebook_VideoPose3D_Inference_in_the_wild_Detectron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Install Pytorch & Caffe2**

In [2]:
!wget https://anaconda.org/pytorch/pytorch-nightly/1.2.0.dev20190722/download/linux-64/pytorch-nightly-1.2.0.dev20190722-py3.6_cuda10.0.130_cudnn7.5.1_0.tar.bz2
!tar xvjf pytorch-nightly-1.2.0.dev20190722-py3.6_cuda10.0.130_cudnn7.5.1_0.tar.bz2
!cp -r lib/python3.6/site-packages/* /usr/local/lib/python3.6/dist-packages/

lib/python3.6/site-packages/torch/for_onnx/__init__.py
lib/python3.6/site-packages/torch/autograd/_functions/__init__.py
lib/python3.6/site-packages/torch/nn/_intrinsic/__init__.py
info/test/run_test.py
lib/python3.6/site-packages/torch/cuda/sparse.py
info/test/test/bottleneck/test.py
lib/python3.6/site-packages/torch/utils/ffi/__init__.py
lib/python3.6/site-packages/torch/utils/model_zoo.py
lib/python3.6/site-packages/torch/nn/qat/__init__.py
lib/python3.6/site-packages/torch/nn/quantized/__init__.py
info/test/test/test_module/no_future_div.py
lib/python3.6/site-packages/torch/version.py
lib/python3.6/site-packages/torch/backends/mkl/__init__.py
lib/python3.6/site-packages/torch/backends/openmp/__init__.py
lib/python3.6/site-packages/torch/backends/mkldnn/__init__.py
lib/python3.6/site-packages/torch/nn/_functions/thnn/__init__.py
info/test/test/data/network1.py
lib/python3.6/site-packages/caffe2/python/onnx/tests/__init__.py
info/test/test/test_module/future_div.py
lib/python3.6/site

# check if Caffe2 was  build

In [3]:
# To check if Caffe2 build was successful
!python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"

# To check if Caffe2 GPU build was successful
!python -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'

Success
1


# Install COCO Dataset 

In [4]:
!apt-get install python-dev
!pip install cython
!pip install pycocotools
!git clone https://github.com/cocodataset/cocoapi.git
!cd cocoapi/PythonAPI && make install

import os
os.environ['COCOAPI'] = ":/content/cocoapi"

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.15~rc1-1).
The following package was automatically installed and is no longer required:
  libnvidia-common-410
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Cloning into 'cocoapi'...
remote: Enumerating objects: 953, done.
remote: Total 953 (delta 0), reused 0 (delta 0), pack-reused 953
Receiving objects: 100% (953/953), 11.70 MiB | 26.44 MiB/s, done.
Resolving deltas: 100% (565/565), done.
# install pycocotools to the Python site-packages
python setup.py build_ext install
running build_ext
cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
/usr/local/lib/python3.6/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /content/cocoapi/PythonAPI/pycocotools/_mask.pyx
  tree = Parsi

# Install Detectron

In [5]:
!git clone https://github.com/facebookresearch/detectron
!pip install -r detectron/requirements.txt
!cd detectron && make
!python detectron/detectron/tests/test_spatial_narrow_as_op.py

Cloning into 'detectron'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 1333 (delta 0), reused 1 (delta 0), pack-reused 1331
Receiving objects: 100% (1333/1333), 4.37 MiB | 18.96 MiB/s, done.
Resolving deltas: 100% (797/797), done.
     |████████████████████████████████| 256kB 3.4MB/s 
  Stored in directory: /root/.cache/pip/wheels/03/05/65/bdc14f2c6e09e82ae3e0f13d021e1b6b2481437ea2f207df3f
Successfully built pyyaml
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
python setup.py develop --user
Compiling detectron/utils/cython_bbox.pyx because it changed.
Compiling detectron/utils/cython_nms.pyx because it changed.
[1/2] Cythonizing detectron/utils/cython_bbox.pyx
/usr/local/lib/python3.6/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will ch

# Install VideoPose3D & Copy Video Script to Detectron Tools Folder

In [6]:
#copy file from VideoPose3d
!git clone https://github.com/facebookresearch/VideoPose3D
!cp VideoPose3D/inference/infer_video.py detectron/tools/infer_video.py

Cloning into 'VideoPose3D'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 98 (delta 0), reused 0 (delta 0), pack-reused 97
Unpacking objects: 100% (98/98), done.


# Download Pretrained Human3.6m Coco Model

In [7]:
!mkdir VideoPose3D/checkpoint
os.chdir('VideoPose3D/checkpoint')
!wget https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_detectron_coco.bin
os.chdir('../..')

--2019-07-25 14:08:03--  https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_detectron_coco.bin
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.20.6.166, 104.20.22.166, 2606:4700:10::6814:6a6, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.20.6.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67892577 (65M) [application/octet-stream]
Saving to: ‘pretrained_h36m_detectron_coco.bin’

pretrained_h36m_det 100%[===================>]  64.75M  28.4MB/s    in 2.3s    

2019-07-25 14:08:06 (28.4 MB/s) - ‘pretrained_h36m_detectron_coco.bin’ saved [67892577/67892577]



# Download Youtube Video for 3D Pose Estimation (specify YOUTUBE_ID)

In [8]:
YOUTUBE_ID ='UpH7rm0cYbM'


!pip install -q youtube-dl
#download video
!youtube-dl -f 'bestvideo[ext=mp4]' --output "youtube.%(ext)s" https://www.youtube.com/watch?v=$YOUTUBE_ID

!mkdir videos   
  
# cut the first 5 seconds
!ffmpeg -y -loglevel info -i youtube.mp4 -ss 00:00:42 -t 00:00:05 videos/video.mp4

# recommendet alternation to 50fps 
#!ffmpeg -i videos/video.mp4 -filter "minterpolate='fps=50'" -crf 0 videos/video50fps.mp4

     |████████████████████████████████| 1.8MB 3.4MB/s 
[youtube] UpH7rm0cYbM: Downloading webpage
[youtube] UpH7rm0cYbM: Downloading video info webpage
[download] Destination: youtube.mp4
[download] 100% of 11.24MiB in 00:00
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-lib

# Compute 2D Coordinates with Detectron

In [9]:
!mkdir output
!python detectron/tools/infer_video.py \
    --cfg detectron/configs/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml \
    --output-dir output \
    --image-ext mp4 \
    --wts https://dl.fbaipublicfiles.com/detectron/37698009/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml.08_45_57.YkrJgP6O/output/train/keypoints_coco_2014_train:keypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
   videos
    
#	  --wts https://dl.fbaipublicfiles.com/detectron/37698009/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml.08_45_57.YkrJgP6O/output/train/keypoints_coco_2014_train:keypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl \

    

Found Detectron ops lib: /usr/local/lib/python3.6/dist-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO io.py: 112: Downloading remote file https://dl.fbaipublicfiles.com/detectron/37698009/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml.08_45_57.YkrJgP6O/output/train/keypoints_coco_2014_train:keypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl to /tmp/detectron-download-cache/37698009/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.ya

# Prepare Detectron Output to fit VideoPose3D Input

In [10]:

!mkdir ./VideoPose3D/data/detectronoutput
!cp output/video.mp4.npz VideoPose3D/data/detectronoutput/video.mp4.npz
os.chdir('VideoPose3D/data') # This script must be launched from the "data" directory
!python prepare_data_2d_custom.py -i detectronoutput -o myvideos
os.chdir('../../')

Parsing 2D detections from detectronoutput
Processing detectronoutput/video.mp4.npz
120 total frames processed
0 frames were interpolated
----------
Saving...
Done.


# Compute 3D Joints with VideoPose3D

In [15]:
#os.chdir('../')

#os.chdir('checkpoint')
#!wget https://dl.fbaipublicfiles.com/video-pose-3d/pretrained_h36m_cpn.bin
##!wget https://dl.fbaipublicfiles.com/video-pose-3d/d-pt-243.bin

!cp ./videos/video.mp4 VideoPose3D/video.mp4
os.chdir('VideoPose3D')


#!python run.py -d custom -k MyCustomDatasetName -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject S1 --viz-action custom --viz-camera 0 --viz-export My3dDataExport --viz-size 6
#!python run.py -d custom -k MyCustomDatasetName -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject  video.mp4 --viz-action custom --viz-camera 0 --viz-video video.mp4 --viz-output output.mp4 --viz-size 6

#!python run.py -e 80 -k gt -arc 3,3,3,3,3


#!python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --viz-export My3dDataExport

#!python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate d-pt-243.bin --render --viz-subject video.mp4 --viz-action Directions --viz-video video.mp4 --viz-camera 0 --viz-output output_scater.mp4 --viz-size 5 --viz-downsample 1 --viz-skip 9

#!python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject video.mp4 --viz-action custom --viz-camera 0 --viz-video video.mp4 --viz-output output.mp4 --viz-size 6
!python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject video.mp4 --viz-action custom --viz-camera 0 --viz-video video.mp4 --viz-output output.mp4 --viz-export outputfile --viz-size 6

#working version 
#!python run.py -k gt -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_cpn.bin --viz-export My3dDataExport --viz-output output.mp4

Namespace(actions='*', architecture='3,3,3,3,3', batch_size=1024, bone_length_term=True, by_subject=False, causal=False, channels=1024, checkpoint='checkpoint', checkpoint_frequency=10, data_augmentation=True, dataset='custom', dense=False, disable_optimizations=False, downsample=1, dropout=0.25, epochs=60, evaluate='pretrained_h36m_detectron_coco.bin', export_training_curves=False, keypoints='myvideos', learning_rate=0.001, linear_projection=False, lr_decay=0.95, no_eval=False, no_proj=False, render=True, resume='', stride=1, subjects_test='S9,S11', subjects_train='S1,S5,S6,S7,S8', subjects_unlabeled='', subset=1, test_time_augmentation=True, viz_action='custom', viz_bitrate=3000, viz_camera=0, viz_downsample=1, viz_export='outputfile', viz_limit=-1, viz_no_ground_truth=False, viz_output='output.mp4', viz_size=6, viz_skip=0, viz_subject='video.mp4', viz_video='video.mp4', warmup=1)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Tr

# Display Results - Joint Export 

In [17]:
#inspect joints export 

import numpy as np
data  = np.load('outputfile.npy')
lst = data
for item in lst:
    print(item)
    


[[-1.84757664e-06 -1.19655415e-05  4.07951774e-07]
 [-1.17904201e-01  5.18989470e-03 -7.73771247e-03]
 [-8.34399462e-02  4.22496229e-01  4.40699346e-02]
 [-6.50798380e-02  8.33848834e-01  1.92969233e-01]
 [ 1.17903978e-01 -5.19633805e-03  7.74077699e-03]
 [ 1.01335093e-01  4.13568616e-01  4.63724211e-02]
 [ 7.70516843e-02  8.22387815e-01  2.04102367e-01]
 [-4.63575125e-03 -2.21408889e-01 -3.40139270e-02]
 [ 2.36371495e-02 -4.67659920e-01 -7.07157850e-02]
 [ 1.09862732e-02 -5.18018842e-01 -1.65461794e-01]
 [ 1.74564421e-02 -6.21216059e-01 -1.19469650e-01]
 [ 1.37549132e-01 -3.93114865e-01 -3.71762551e-02]
 [ 2.15850085e-01 -1.63755655e-01  5.29122613e-02]
 [ 2.30838135e-01 -3.21006253e-02 -1.20244250e-01]
 [-1.01513952e-01 -4.07361925e-01 -5.73270991e-02]
 [-2.15715230e-01 -1.90889627e-01  1.78241096e-02]
 [-1.96710110e-01 -4.43495736e-02 -1.60484672e-01]]
[[-2.12354280e-06 -1.16421634e-05  5.56914415e-07]
 [-1.17669448e-01  4.66085970e-03 -6.63583539e-03]
 [-8.35900083e-02  4.21773225e

# Display Results - Joint Video

In [18]:
#display video
def show_local_mp4_video(file_name, width=640, height=480):
  import io
  import base64
  from IPython.display import HTML
  video_encoded = base64.b64encode(io.open(file_name, 'rb').read())
  return HTML(data='''<video width="{0}" height="{1}" alt="test" controls>
                        <source src="data:video/mp4;base64,{2}" type="video/mp4" />
                      </video>'''.format(width, height, video_encoded.decode('ascii')))

show_local_mp4_video('output.mp4', width=960, height=720)

#Download Joint Export & Video

In [0]:
from google.colab import files


files.download('output.mp4')
files.download('outputfile.npy')